name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 0 * * *"   # 每天更新一次
  workflow_dispatch:        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - uses: actions/checkout@v4

      - uses: stats-organization/github-readme-stats-action@main
        with:
          USERNAME: BJ4501
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
